## Consider the Given “Iris” data set and  classify iris flowers among three species (setosa, versicolor, or virginica) from measurements of sepals and petals' length and width.

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing

In [2]:
# load the iris data
df = pd.read_csv('iris.csv')
df.head(5)

sepal.length  sepal.width  petal.length  petal.width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

array([0, 1, 2], dtype=int32)

In [4]:
# select features
y = df['species_label'] #Dependent feature
X = df[['sepal.length', 'sepal.width']] #Independent features (subset)

In [5]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=0)

In [6]:
# train the decision tree
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [7]:
# testing the model
y_pred = dtree.predict(X_test)

In [8]:
#acuuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 0.67


In [9]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 1  5 12]
 [ 0  2  9]]


## Increasing the accuracy value

In [10]:
# select features
y = df['species_label'] #Dependent feature
X = df[['sepal.length', 'sepal.width','petal.length','petal.width']] #Independent features (subset)

In [11]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=0)

In [12]:
# train the decision tree
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [13]:
# testing the model
y_pred = dtree.predict(X_test)

In [14]:
#acuuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 0.98


In [15]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
