## Consider the Given “Iris” data set and classify iris flowers among three species (setosa, versicolor, or virginica) from measurements of sepals and petals' length and width using KNN algorithm.

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv('iris.csv')
y=df.iloc[:,-1].values  
x=df.iloc[:,0:4].values  
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [12]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
print(x_train)
print(x_test)

[[-0.09771611 -0.15234084  0.32025359  0.05966963]
 [ 1.85660612 -0.38374465  1.5035953   0.82685054]
 [ 1.12373528 -0.15234084  0.77105043  0.69898705]
 [ 1.12373528  0.07906297  0.60200161  0.44326008]
 [ 0.14657417  0.31046678  0.65835122  0.82685054]
 [-0.95273209  1.0046782  -1.14483614 -0.70751128]
 [ 0.51300958  0.77327439  0.99644885  1.46616796]
 [-0.83058695  0.77327439 -1.20118575 -1.21896522]
 [-0.34200639 -1.30935988  0.20755438  0.18753311]
 [ 0.26871931 -2.00357131  0.20755438 -0.19605734]
 [-0.83058695  1.69888963 -1.14483614 -1.21896522]
 [-0.34200639  1.0046782  -1.31388496 -1.21896522]
 [-0.09771611  3.08731248 -1.20118575 -0.96323825]
 [ 0.75729986 -0.61514846  1.10914806  1.21044099]
 [-1.07487723  0.07906297 -1.20118575 -1.34682871]
 [-0.46415153  0.77327439 -1.08848654 -1.21896522]
 [ 0.39086445 -0.61514846  0.20755438  0.18753311]
 [ 1.97875126 -0.61514846  1.39089609  0.95471402]
 [ 1.12373528  0.54187058  1.16549766  1.21044099]
 [-1.19702236 -0.15234084 -1.25

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=12)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)

['Virginica' 'Setosa' 'Versicolor' 'Setosa' 'Virginica' 'Versicolor'
 'Versicolor' 'Virginica' 'Virginica' 'Versicolor' 'Versicolor'
 'Versicolor' 'Virginica' 'Virginica' 'Setosa' 'Versicolor' 'Virginica'
 'Virginica' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Versicolor'
 'Setosa' 'Virginica' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Versicolor']


In [14]:
from sklearn.metrics import confusion_matrix

c=confusion_matrix(y_test,y_pred)  
print(c)

[[ 6  0  0]
 [ 0 12  0]
 [ 0  1 11]]
