## Implement a perceptron network for the table given below

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivation(x):
    return x*(x-1)

In [4]:
input = np.array([[0,0,1],
                  [1,1,1],
                  [1,0,1],
                  [0,1,1]])

In [5]:
a_output = np.array([[0,1,1,0]]).T

In [6]:
np.random.seed(1)

In [7]:
weights = 2* np.random.random((3,1)) - 1

In [8]:
print('Initial weights are:')
print(weights)

Initial weights are:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [9]:
for i in range(10000):
    input_layer = input
    o_output = sigmoid(np.dot(input_layer, weights))
  
    loss = o_output - a_output

    adjustment = loss * sigmoid_derivation(o_output)

    weights = weights + np.dot(input_layer.T, adjustment)


In [10]:
print('new weights are:')
print(weights)

new weights are:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [11]:
print('obtained output values are')
print(o_output)

obtained output values are
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]
